queue_rules:
  - name: default
    queue_conditions:
      - check-success=ci
      - -draft
      - -conflict
    merge_conditions:
      - check-success=ci
    merge_method: squash
    batch_size: 5
    batch_max_wait_time: 15 minutes
    checks_timeout: 60 minutes

merge_queue:
  max_parallel_checks: 1

merge_protections_settings:
  reporting_method: check-runs
  auto_merge_conditions:
    - or:
        - label = trivial
        - label = mergify-approve
    - label != do-not-merge

merge_protections:
  - name: required CI
    if:
      - -closed
    success_conditions:
      - check-success=ci
