queue_rules:
  - name: default
    queue_conditions:
      - check-success=ci
      - -draft
      - -conflict
    merge_conditions:
      - check-success=ci
    merge_method: squash
    batch_size: 5
    batch_max_wait_time: 15 minutes

merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: queue PRs with mergify-approve label
    conditions:
      - or:
          - label = trivial
          - label = mergify-approve
      - label != do-not-merge
      - -draft
      - -closed
    actions:
      queue:
        name: default
